### PR TITLE
Undo mp base adapter

### PR DESCRIPTION
**Pull request by mzeshan39**
Hi Hisashi,

Can you review the code and please let me know if you want me to improve anything or change anything.

Thanks
Zeshan

### CODE REVIEW

**Review by himi — COMMENTED** [review]
In this change, please do not change the bundle version in MANIFEST.MF.  We will soon need to change at least minor version by this change.
The change of the signature of set-methods is grave and will give a fallback method.  I'll consider some implementation

**Comment by mzeshan39** [comment]
set has an implementation in BaseAdapter and DefaultAdapter it doesn't have the implementation on the test project.

**Comment by himi** [comment]
I restored the original  void set(EObject eObj, EStructuralFeature feature, Object value) throws MPException;  @mzeshan39 do you really need a new method with oldValue?  One concern I come up with is the current MPBaseAdapter does no support transactional view and maybe the SPI user needs to specify oldValue in an explicit manner, but that style looks quite special.  I think the current set method without oldValue is sufficient.  If you agree on it, I will remove the new method with oldValue.

**Comment by mzeshan39** [comment]
yeah sure, you can remove the method.

**Review by himi — APPROVED** [review]

**Comment by himi** [comment]
@mzeshan39 please review the changes and then merge it into the master.

**Comment by mzeshan39** [comment]
@himi sure I'll check the changes and merge it into master

**Comment by mzeshan39** [comment]
@himi  I review the changes and merge them into the master branch and pushed.

**Pull request merged**
